services:
  - type: web
    name: tcc-ia-api
    env: python
    buildCommand: cd Backend && pip install -r requirements.txt
    startCommand: cd Backend && python -m flask run
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production 